data:
  iters_per_epoch: None 

log:
  checkpoint_freq: 50 
  root: '?'
  metrics:
    dice_score:
      _fn: ionpy.metrics.dice_score
      from_logits: True
      batch_reduction: 'mean' 
      ignore_empty_labels: True
    ece_loss:
      _fn: ese.metrics.image_ece_loss
      from_logits: True
      num_prob_bins: 15
    edge_ece_loss:
      _fn: ese.metrics.image_edge_ece_loss
      from_logits: True
      num_prob_bins: 15
      neighborhood_width: 3
    elm_loss:
      _fn: ese.metrics.image_elm_loss
      class_weighting: 'proportional'
      from_logits: True
      num_prob_bins: 15
      neighborhood_width: 3

# AUGMNENTATIONS USED FOR CITYSCAPES
augmentations:
    train:
        - Resize:
            height: 256
            width: 512
        - HorizontalFlip:
            p: 0.5
    val:
        - Resize: # Maybe strange to do this, but we want to be able to compare the results.
            height: 256
            width: 512