data:
  iters_per_epoch: 100

log:
  checkpoint_freq: 50 
  root: '?'
  metrics:
    dice_score:
      _fn: ionpy.metrics.dice_score
      batch_reduction: 'mean' 
      ignore_empty_labels: False 
      from_logits: True
    ece_loss:
      _fn: ese.metrics.image_ece_loss
      num_prob_bins: 15
      from_logits: True
    edge_ece_loss:
      _fn: ese.metrics.image_edge_ece_loss
      num_prob_bins: 15
      neighborhood_width: 3
      from_logits: True