train:
  epochs: 3000
  eval_freq: 20

data:
  iters_per_epoch: null 

dataloader:
  batch_size: '?' 

optim:
  lr: '?'

log:
  checkpoint_freq: 50
  root: '?'
  metrics:
    dice_score:
      _fn: ionpy.metrics.dice_score
      batch_reduction: 'mean' 
      ignore_empty_labels: False 
      from_logits: True
    ece_loss:
      _fn: ese.metrics.image_ece_loss
      num_prob_bins: 15
      from_logits: True