train:
  epochs: 3000
  eval_freq: 10

data:
  _class: ese.datasets.OCTA_6M
  in_channels: 1
  out_channels: 1 
  label: 255 # Two options, 100 and 255 (center or vessels)
  version: 1.0 # Two options, 0.1 and 1.0 (128x128 or 400x400 res)
  label_threshold: 0.5 # The default is to train on hard labels.
  train_kwargs:
      split: 'cal'
      iters_per_epoch: 1000 
  val_kwargs:
      split: 'val'

dataloader:
  batch_size: 4 
  num_workers: 2 