
train:
  epochs: 3000
  eval_freq: 30 

data:
  _class: ese.datasets.Roads
  version: 0.1
  in_channels: 3
  out_channels: 1 
  train_kwargs:
    split: 'cal'
    transforms:
      - albumentations.RandomCrop:
          height: 500
          width: 500
  val_kwargs: 
    split: 'val'
    transforms:
      - albumentations.RandomCrop:
          height: 500
          width: 500

dataloader:
  batch_size: 4
  num_workers: 2