data:
  return_dst_to_bdry: False 
  iters_per_epoch: 250 

log:
  checkpoint_freq: 50 
  root: '?'
  metrics:
    dice_score:
      _fn: ionpy.metrics.dice_score
      from_logits: True
      batch_reduction: 'mean' 
      ignore_empty_labels: False 
    ece_loss:
      _fn: ese.metrics.image_ece_loss
      from_logits: True
      num_prob_bins: 15
    edge_ece_loss:
      _fn: ese.metrics.image_edge_ece_loss
      from_logits: True
      num_prob_bins: 15
      neighborhood_width: 3

# AUGMNENTATIONS USED FOR BETTER CALIBRATION (Should these be the same as training?)
augmentations:
    val:
      - HorizontalFlip:
          p: 0.5
      - Rotate:
          limit: 10
          p: 0.5
      - RandomScale:
          scale_limit: [0.5, 2]
          p: 0.5
      - GaussianBlur:
          blur_limit: [3, 7]
          p: 0.5
      - RandomBrightnessContrast:
          p: 0.5
      - Resize:
          height: 256
          width: 256
      - ToFloat
    cal:
      - ToFloat