image_cal_metrics:
    # ECE Metrics
    #########################################################
    - Image_ECE:
        _fn: ese.metrics.calibration.image_ece_loss
        cal_type: 'toplabel'

# Define global metrics when you want to verify that these are the same as the image
# based metrics, per image.
global_cal_metrics:
    # ECE Metrics
    ########################################################
    - ECE:
        _fn: ese.metrics.calibration.ece_loss
        cal_type: 'toplabel'