experiment: 
    inf_kwargs:
        from_logits: True
        threshold: 0.5 
        temperature: 1.0

log:
  track_label_amounts: True 

global_calibration:
    num_classes: 1

inference_data:
  split: ("cal", "val")

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        batch_reduction: 'mean' 
        ignore_empty_labels: False
        metric_type: quality
    
dataloader:
    batch_size: 4
    num_workers: 2