experiment: 
    inf_kwargs:
        from_logits: True
        threshold: 0.5 
        temperature: 1.0
        patch_pred_kwargs: # We need to do patch based inference because native res is 1500x1500
            combine_fn: 'cat'
            dims:
                height: 500 
                width: 500

inference_data:
  split: ("cal", "val")

dataloader:
    batch_size: 8 
    num_workers: 3 

log:
  track_label_amounts: True 

global_calibration:
    num_classes: 1

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        batch_reduction: 'mean' 
        ignore_empty_labels: False
        metric_type: quality