log:
  track_label_amounts: True 
  min_fg_pixels: 0

inference_data:
  input_type: image 
  subsplit: '0'

global_calibration:
    num_classes: 2

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        from_logits: True
        batch_reduction: 'mean' 
        ignore_index: 0
        metric_type: quality