experiment: 
    inf_kwargs:
        from_logits: True
        threshold: 0.5 
        temperature: 1.0

dataloader:
  batch_size: 4
  num_workers: 4

inference_data:
  split: ("cal", "val")


global_calibration:
    num_classes: 1

log:
  track_label_amounts: True 
  min_fg_pixels: 1

model:
    pred_label: 0

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        batch_reduction: 'mean' 
        ignore_empty_labels: False
        metric_type: quality