data:
  _class: ese.datasets.ACDC
  in_channels: 1
  out_channels: 1 
  version: 0.1
  iters_per_epoch: 500 
  preload: False 

dataloader:
  batch_size: 8
  num_workers: 1

log:
  root: '?'
  checkpoint_freq: 20 
  metrics:
    dice_score:
      _fn: ionpy.metrics.dice_score
      batch_reduction: 'mean' 
      ignore_empty_labels: False 
      from_logits: True
    ece_loss:
      _fn: ese.metrics.image_ece_loss
      num_prob_bins: 15
      from_logits: True
    edge_ece_loss:
      _fn: ese.metrics.image_edge_ece_loss
      num_prob_bins: 15
      neighborhood_width: 3
      from_logits: True

model:
  filters: [64, 64, 64, 64, 64]
  convs_per_block: 3

train:
  epochs: 1000
  eval_freq: 10 

# Stndard segmentation data augmentation.
# augmentations:
#     train:
#         - albumentations.ElasticTransform:
#             alpha: 90 
#             sigma: 7 
#             alpha_affine: 0 
#             p: 0.5
#             always_apply: True
#         - albumentations.Flip:
#             p: 0.5
#         - ese.experiment.augmentation.SVLS: # SVLS
#             ksize: 3
#             sigma: 1
#             always_apply: True
#             include_center: True 