data:
  _class: ese.datasets.ISLES
  in_channels: 1
  out_channels: 1 
  version: 1.0 

dataloader:
  batch_size: 4
  num_workers: 2 # 3D data can be a bottleneck

optim:
  lr: 1.0e-05

log:
  root: '?'
  checkpoint_freq: 30 
  metrics:
    dice_score:
      _fn: ionpy.metrics.dice_score
      from_logits: True
      batch_reduction: 'mean' 
      ignore_empty_labels: False 
    proportion_estimation_error:
      _fn: ese.losses.area_estimation_error
      from_logits: True
      proportion: True
      abs_diff: True
      square_diff: False
    image_ece:
      _fn: ese.metrics.image_ece_loss
      from_logits: True
      num_prob_bins: 15


model:
  filters: [64, 64, 64, 64, 64, 64, 64]
  dims: 3
  convs_per_block: 3

train:
  epochs: 3000
  eval_freq: 30 
