data:
  _class: ese.datasets.OASIS
  axis: 1
  label_set: label35
  num_slices: 1
  in_channels: 1
  central_width: 32
  version: 0.2
  out_channels: 2 
  binary: True 
  target_labels:
    - 7
    - 26
  iters_per_epoch: 1000 
  preload: '?' 