data:
  _class: ese.datasets.OCTA_6M
  in_channels: 1
  out_channels: 1 
  label: 255 # Two options, 100 and 255 (center or vessels)
  version: 1.0 # Two options, 0.1 and 1.0 (128x128 or 400x400 res)
  label_threshold: 0.5 # The default is to train on hard labels.
  preload: False 

dataloader:
  batch_size: 4
  num_workers: 4

log:
  root: '?'
  checkpoint_freq: 10 
  metrics:
    dice_score:
      _fn: ionpy.metrics.dice_score
      batch_reduction: 'mean' 
      ignore_empty_labels: False 
      from_logits: True

model:
  filters: [64, 64, 64, 64, 64, 64]
  convs_per_block: 3

train:
  epochs: 3000
  eval_freq: 10 